######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 17 11:21:19 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += header.h
FORMS += header.ui
SOURCES += header.cpp header2011.cpp
